# Site settings
title: Blog
header-img: img/home-bg.png
email: hredleaf@gmail.com
copyright_name: hailuhr
description: > # this means to ignore newlines until "baseurl:"
  Create
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  hailuhr
learn_profile: hailuhr
email_username: hredleaf@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
